spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        #        show_sql: true # sout으로 출력
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace